# Generated by Django 3.1.4 on 2020-12-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factreview',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yelp_reviews.dimdate'),
        ),
    ]
