# Generated by Django 3.1.4 on 2020-12-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_reviews', '0006_auto_20201212_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factreview',
            name='id',
        ),
        migrations.AlterField(
            model_name='factreview',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yelp_reviews.dimdate'),
        ),
    ]
